[[middleware]]
    id="@middleware-a"
    funcStmt=["""func(){
                fmt.Println("")
            }()
        """]
    deferStmt=["""defer func(){
                fmt.Println("")
            }()
        """]
    [[middleware.package]]
        name = "f"
        path = "fmt"

[[middleware]]
    id="@middleware-b"
    funcStmt=["""func(){
                    fmt.Println("middleware-b install")
                }()
            """]
    deferStmt=["""defer func(){
                    fmt.Println("middleware-b install")
                }()
            """]
    [[middleware.package]]
        name = "f"
        path = "fmt"