[[middleware]]
id="@middleware-a"
    [[middleware.Stmt]]
    kind="add-func-without-depends"
    code=["""func(){
                    log.Println("before")
                }()"""]
    depend=["err"]
    [[middleware.Stmt]]
    kind="add-func-with-var-depend"
    code =["""func(){
                    log.Println("before")
                }()"""]
    depend=["str"]
    [[middleware.package]]
    name = "log"
    path = """ "github.com/sirupsen/logrus" """