[[middleware]]
    id="@middleware-a"
    funcStmt=["""func(){
                log.Println("before")
            }()
        """]
    deferStmt=["""defer func(){
                log.Println("defer")
            }()
        """]
    [[middleware.package]]
        name = "log"
        path = """ "github.com/sirupsen/logrus" """

[[middleware]]
    id="@middleware-b"
    funcStmt=["""func(){
                    log.Println("middleware-b install")
                }()
            """]
    deferStmt=["""defer func(){
                    log.Println("middleware-b install")
                }()
            """]
    [[middleware.package]]
        name = "log"
        path = """ "github.com/sirupsen/logrus" """